package com.sarpamitra.referral

import android.graphics.Bitmap
import android.graphics.Color
import com.google.zxing.BarcodeFormat
import com.google.zxing.EncodeHintType
import com.google.zxing.qrcode.QRCodeWriter

object QrGenerator {

    fun generate(content: String, size: Int = 400): Bitmap {
        val hints = mapOf(EncodeHintType.MARGIN to 1)
        val writer = QRCodeWriter()
        val matrix = writer.encode(content, BarcodeFormat.QR_CODE, size, size, hints)
        val bitmap = Bitmap.createBitmap(size, size, Bitmap.Config.RGB_565)
        for (x in 0 until size) {
            for (y in 0 until size) {
                bitmap.setPixel(x, y, if (matrix[x, y]) Color.BLACK else Color.WHITE)
            }
        }
        return bitmap
    }

    fun buildQrContent(
        caseId: String,
        severity: String,
        syndrome: String,
        asvRequired: Boolean,
        asvType: String?,
        estimatedVials: Int?,
        timestamp: Long
    ): String {
        return """
SARPA-MITRA EMERGENCY REFERRAL
Case ID: $caseId
Severity: $severity
Syndrome: $syndrome
ASV Required: ${if (asvRequired) "YES" else "NO"}
ASV Type: ${asvType ?: "N/A"}
Vials: ${estimatedVials ?: "N/A"}
Time: ${java.text.SimpleDateFormat("dd-MM-yyyy HH:mm", java.util.Locale.getDefault()).format(java.util.Date(timestamp))}
Generated by Sarpa-Mitra offline AI
        """.trimIndent()
    }
}